### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by ghost** [liquidz/misaki#41]
I keep getting this every time I try running the sample/blog. Not sure what's the problem. here..

****@ubuntu:~/misaki$ lein run sample/blog
Exception in thread "main" java.io.FileNotFoundException: sample/blog/_config.clj (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at clojure.java.io$fn__8638.invoke(io.clj:233)
    at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
    at clojure.java.io$fn__8650.invoke(io.clj:262)
    at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
    at clojure.java.io$fn__8612.invoke(io.clj:169)
    at clojure.java.io$fn__8551$G__8546__8558.invoke(io.clj:73)
    at clojure.java.io$reader.doInvoke(io.clj:106)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$slurp.doInvoke(core.clj:6278)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at misaki.config$read_config.invoke(config.clj:65)
    at misaki.config$make_basic_config_map.invoke(config.clj:95)
    at misaki.server$_main.doInvoke(server.clj:89)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at user$eval37.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6609)
    at clojure.lang.Compiler.eval(Compiler.java:6582)
    at clojure.core$eval.invoke(core.clj:2852)
    at clojure.main$eval_opt.invoke(main.clj:308)
    at clojure.main$initialize.invoke(main.clj:327)
    at clojure.main$null_opt.invoke(main.clj:362)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)

**Comment by liquidz** [comment]
Try `lein run samples/blog` instead of `lein run sample/blog`.

**Comment by ghost** [comment]
that would be it!
どうもありがとうございました！

**Comment by ghost** [comment]
I'm having trouble with deployment.

I've been trying to get the site up on heroku, but when ever I try using foreman, I get this error:

*_**@ubuntu:~/misaki$ foreman start
19:22:15 web.1  | started with pid 14866
19:22:20 web.1  | *_\* Warning: This project requires Leiningen version 2.0.0 ***
19:22:20 web.1  | **\* Using version 1.6.1 could cause problems. ***
19:22:20 web.1  | - Get the latest verison of Leiningen at
19:22:20 web.1  | - https://github.com/technomancy/leiningen
19:22:20 web.1  | - Or by executing "lein upgrade"
19:22:21 web.1  | No :main namespace specified in project.clj.
19:22:21 web.1  | exited with code 1
19:22:21 system | sending SIGTERM to all processes
SIGTERM received

And whenever I try pushing up to the Heroku, I get this exception during the build:
****@ubuntu:~/misaki$ git push heroku master
....
 Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: some-> in this context, compiling:(misaki/util/file.clj:112)
.... (long stack trace)

Here's what's in my Procfile and my project.clj (my blog name is alphonse23.github.com): 
****@ubuntu:~/misaki$ cat Procfile
web: lein run alphonse23.github.com

****@ubuntu:~/misaki$ cat project.clj
(defproject hello-world "0.0.1"
  :dependencies [[org.clojure/clojure "1.4.0"]
                 [ring/ring-jetty-adapter "1.1.0"]]
  :min-lein-version "2.0.0")

Even if I can't deploy my blog I think misaki is pretty awesome in either case!

**Comment by liquidz** [comment]
I apologise for the delay in replying to you.

To use `some->` function, you should use clojure 1.5 or later.
https://github.com/clojure/clojure/blob/master/changes.md

So would you change your project.clj to use clojure 1.5.1?

**Comment by ghost** [comment]
Sorry liquidz. I couldn't get back to this issue because my computer broke, so I can't look at the old set up anymore. Thank you for the help anyway. どうもありがとうございました.

**Comment by solussd** [comment]
The wiki docs need to refer to `lein run samples/blog` still.
